# Generated by Django 5.1.3 on 2024-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
